routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('/', function () {
    return view('welcome');
});

// Route::get('/', 'FoodController@index');
// Route::post('/create', 'FoodController@create');
// Route::get('/edit/{id}', 'FoodController@edit');
// Route::post('/update/{id}', 'FoodController@update');
// Route::get('/destroy/{id}', 'FoodController@destroy');

Route::name('food.')->prefix('')->group(function(){
    Route::name('index')->get('','FoodController@index');
    Route::name('create')->post('create','FoodController@create');
    Route::name('edit')->get('{id}/edit','FoodController@edit');
    Route::name('update')->post('{id}','FoodController@update');
    Route::name('destroy')->get('{id}','FoodController@destroy');
});

app/Food.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Food extends Model
{
    use SoftDeletes;

    protected $table = 'food';
    protected $fillable = ['id', 'name', 'description', 'price', 'pic'];

    protected $dates = ['deleted_at'];
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/FoodApiController.php
<?php

namespace App\Http\Controllers;

use App\Food;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class FoodApiController extends Controller
{
    public function index(){
        $food = Food::all();
        return response()->json($food);
    }
    public function create(request $request){
        
        $request->validate([
            'name' => 'required',
            'price' => 'required'
        ]);
        
        $food = new Food;
        $food -> name = $request-> name;
        $food -> description = $request-> description;
        $food -> price = $request-> price;
        $food -> pic = $request-> pic;
        $food->save();

        return response()->json(["success" => true, "message" => "data added"]);
    }
    public function update(request $request, $id){

        $request->validate([
            'name' => 'required',
            'price' => 'required'
        ]);

        $food = Food::find($id);
        if(!$food){
            return response()->json(["error" => true, "message" => "id not found"]);
        }
        
        $food -> name = $request-> name;
        $food -> description = isset($request-> description)? $request-> description : $food -> description;
        $food -> price = $request-> price;
        $food -> pic = isset($request-> pic)? $request-> pic : $food -> pic;
        $food->save();
        return response()->json(["success" => true, "message" => "updated"]);
    }
    public function destroy($id){
        $food = Food::find($id);
        if(!$food){
            return response()->json(["error" => true, "message" => "id not found"]);
        }
        $food->delete();

        return response()->json(["success" => true, "message" => "deleted"]);
    }
}

app/Http/Controllers/FoodController.php
<?php

namespace App\Http\Controllers;

use App\Food;
use Illuminate\Http\Request;

class FoodController extends Controller
{
    public function index(Request $request)
    {
        $allFood = Food::all();
        return view('food.view', ['foodData' => $allFood]);
    }

    function create(Request $request)
    {
        $submit = $request->all();

        $this->validate($request, [
            'name' => 'required',
            'price' => 'required|integer'
        ]);

        $food = new Food;
        $food->id = $submit['id'];
        $food->name = $submit['name'];
        $food->description = $submit['description'];
        $food->price = $submit['price'];
        $food->pic = $submit['pic'];
        $food->save();

        return redirect('/')->with('success', 'New data has been added!');
    }

    function edit($id)
    {
        $food = Food::find($id);
        if(!$food){
            return redirect('/')->with('error','Item with id: $id not found!');
        }
        return view('food.edit', ['foodData' => $food]);
    }

    function update(Request $request, $id)
    {
        $request->validate([
            'name' => 'required',
            'price' => 'required'
        ]);

        $food = Food::find($id);
        if(!$food){
            return redirect('/')->with('error','Item with id: $id not found!');
        }
        
        $food -> name = $request-> name;
        $food -> description = $request-> description;
        $food -> price = $request-> price;
        $food -> pic = $request-> pic;
        $food->save();

        return redirect('/')->with('success', 'Data saved succesfully!');
    }

    function destroy(Request $request, $id)
    {
        $food = Food::find($id);
        
        if(!$food){
            return redirect('/')->with('error','Item with id: $id not found!');
        }
        $food->delete($request);
        return redirect('/')->with('success', 'Data has been deleted!');
    }
}

resources/views/food/edit.blade.php
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<html>

<head>
</head>

<body>
	<form method="post" action="/{{$foodData->id}}">
		{{ csrf_field() }}
		<div class="mt-5">
			<div class="mx-auto" style="width: 90%;">
				<table class="table table-borderless">
					<tr>
						<input type="hidden" name="id" value="{{ $foodData->id }}">
					</tr>
					<!-- <tr>
						<td>ID</td>
						<td><input class="form-control" type="text" placeholder="ID" name="id" value="{{ $foodData->id }}"></td>
					</tr> -->
					<tr>
						<td>Name</td>
						<td><input class="form-control" type="text" placeholder="Name" name="name" value="{{ $foodData->name }}"></td>

					</tr>
					<tr>
						<td>Description</td>
						<td><input class="form-control" type="text" placeholder="Description" name="description" value="{{ $foodData->description }}"></td>

					</tr>
					<tr>
						<td>Price</td>
						<td><input class="form-control" type="text" placeholder="Price" name="price" value="{{ $foodData->price }}"></td>

					</tr>
					<tr>
						<td>Picture</td>
						<td><input class="form-control" type="text" placeholder="pic" name="pic" value="{{ $foodData->pic }}"></td>

					</tr>
					<tr>
						<td colspan="2">
							<center><input class="btn btn-primary btn-lg btn-block" type="submit" value="Save">
						</td>

					</tr>
				</table>
	</form>
</body>

</html>

resources/views/food/view.blade.php
<html>

<head>
    <title></title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>

<body>
    <div class="mt-5">
        <div class="mx-auto" style="width: 90%;">

            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#modalAdd">
                Add Menu
            </button>
            <br>
            <br>
            @if(session('success'))
            <div class="alert alert-success" role="alert">
                {{session('success')}}
            </div>
            @endif
            <table class="table table-bordered table-sm table-hover">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>NAME</th>
                        <th>DESCRIPTION</th>
                        <th>PRICE</th>
                        <th>PIC</th>
                        <th>ACTION</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($foodData as $item)
                    <tr>
                        <td>{{$item->id}}</td>
                        <td>{{$item->name}}</td>
                        <td>{{$item->description}}</td>
                        <td>{{$item->price}}</td>
                        <td><center><img src="/gambar/{{$item->pic}}" width="128" height="100"></center></td>
                        <td width="20%">
                            <a class="btn btn-primary  btn-sm" href="{{$item->id}}/edit/" role="button">Edit</a>
                            <a class="btn btn-danger  btn-sm" method="delete" href="{{ route('food.destroy', ["id" => $item->id]) }}" role="button">Delete</a>
                    </tr>
                    @endforeach
                </tbody>
            </table>

            <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
            <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
            <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

            <!-- Modal TAMBAH -->
            <div class="modal fade" id="modalAdd" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">Add Menu</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <form method="post" action="/create">
                                {{ csrf_field() }}
                                <div class="">
                                    <table class="table table-borderless  table-sm">
                                        <tr>
                                            <input type="hidden" name="id" required="">
                                        </tr>
                                        <!-- <tr>
                                            <td>ID</td>
                                            <td><input class="form-control" type="text" placeholder="Food ID" name="id"></td>
                                        </tr> -->
                                        <td>Name</td>
                                        <td>
                                            <input class="form-control" type="text" placeholder="Food name" name="name">
                                        </td>
                                        </tr>
                                        <tr>
                                            <td>Descsription</td>
                                            <td><input class="form-control" type="text" placeholder="Food description" name="description"></td>

                                        </tr>
                                        <tr>
                                            <td>Price</td>
                                            <td><input class="form-control" type="text" placeholder="Food price" name="price"></td>

                                        </tr>
                                        <tr>
                                            <td>Picture</td>
                                            <td><input class="form-control" type="text" placeholder="Pic file" name="pic">

                                            </td>

                                        </tr>
                                        <tr>
                                            <td colspan="2">
                                                <center><input class="btn btn-primary btn-lg btn-block" type="submit" value="Insert">
                                            </td>
                                        </tr>
                                    </table>
                            </form>
                        </div>
                        <div class="modal-footer">
                    </div>
                </div>
            </div>
        </div>
</body>

</html>